name: comet
region: nyc
services:
  - name: server
    image:
      registry_type: DOCKER_HUB
      registry: joincomet
      repository: server
      tag: <TAG>
    instance_count: 1
    instance_size_slug: basic-s
    http_port: 4000
    routes:
      - path: /
    envs:
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: CA_CERT
        value: ${db.CA_CERT}
      - key: ACCESS_TOKEN_SECRET
        value: abc123
      - key: BUCKET
        value: https://media.stiforr.tech.nyc3.digitaloceanspaces.com/
      - key: AWS_ACCESS_KEY_ID
        value: <AWS_ACCESS_KEY_ID>
      - key: AWS_SECRET_ACCESS_KEY
        value: <AWS_SECRET_ACCESS_KEY>
      - key: AWS_ENDPOINT
        value: nyc3.digitaloceanspaces.com
      - key: MEDIA_DOMAIN
        value: https://media.stiforr.tech.nyc3.digitaloceanspaces.com/
      # - key: SENTRY_DSN
      #   value: <SENTRY_DSN>
      - key: COMET_USER_PASSWORD
        value: <COMET_USER_PASSWORD>
databases:
  - name: db
    engine: PG
    production: true
    cluster_name: comet
    db_name: defaultdb
    db_user: doadmin
domains:
  - domain: api.stiforr.tech
    type: PRIMARY
